Feat authentication
hinanshisuthar/paw-pedia pull request #4
Opened 2022-05-08 19:19 UTC by hinanshisuthar

Authentication
- user can now login/signup and also log out

2022-05-11 17:53 UTC, adith-a-danthi requested changes
Clean UI. Login and Signup functionality doesn't seem to be working. Some suggestions and changes are mentioned.

2022-05-11 17:53 UTC, adith-a-danthi commented on src/App.js
> +import { Profile } from "./pages/Profile/Profile";
You can use barrel imports for `pages` and `components`

2022-05-11 17:53 UTC, adith-a-danthi commented on src/components/Categories/Categories.jsx
> +            </button> */}
You can remove commented code, if not needed

2022-05-11 17:53 UTC, adith-a-danthi commented on src/reducer/dataReducer.js
> +              }))]
I think, just the spread operator on the payload should be enough, the `map` function is probably unnecessary.

2022-05-11 17:53 UTC, adith-a-danthi commented on src/pages/Authentication/Login.jsx
> +  }, [loginCredentials.email, loginCredentials.password]);
Since the state variable is updated every time the input fields are updated, it isn't a good idea to implement the API call this way. It would be better if it's triggered on a button click.

2022-05-11 17:53 UTC, adith-a-danthi commented on src/pages/Authentication/Signup.jsx
> +  ]);
- The API call should be made on a button click in this scenario. In this implementation multiple unnecessary API calls are made.
- In the dependency list, since you want it to execute for every property you can just pass the state `signupCredentials`

2022-05-21 09:26 UTC, Hamdrive reviewed
Good work on the file structure
Mockman route and component can be removed before pushing to production
@adith-a-danthi has given good suggestions and fixes do implement those

2022-05-21 16:29 UTC, hinanshisuthar commented on src/App.js
> +import { Profile } from "./pages/Profile/Profile";
working now.

2022-05-21 18:20 UTC, hinanshisuthar commented
Made necessary changes and merging

2022-05-21 18:51 UTC, merged